### ISSUE TITLE
add cc-by license

### ISSUE THREAD

**Issue by jcolomb** [open-make/openmakewebsite#19]
I would put the text of the whole website under CC-BY license, adding the license in the footer.

everybody agrees ?

**Comment by MoritzMaxeiner** [comment]
Since we use the website content as information about the project I would say place everythin in the content folder under `CC BY-ND`, instead of raw `CC BY`. Rest should be ok as `CC-BY`, except `themes/hugo-universal-theme`, that's already under `MIT` license, which we ought to keep.

**Comment by jcolomb** [comment]
CC-BY-ND is pretty useless, who would like to take this and repost it without modification (which also means one cannot quote it)?
Apart from standards description, I do not see where CC-BY-ND makes sense.

**Comment by MIE5R0** [comment]
CC-BY is perfectly fine for me.

**Comment by jcolomb** [comment]
added in #18
